# Generated by Django 3.1.7 on 2021-03-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('django_email_log', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='email',
			name='readed',
			field=models.BooleanField(blank=True, db_index=True, default=False),
		),
		migrations.AlterField(
			model_name='email',
			name='success',
			field=models.BooleanField(db_index=True, null=True),
		),
	]
